### DISCUSSION TITLE
Loading raw TM file

### DISCUSSION THREAD

**Discussion by jmwislez** [yamcs/yamcs#717] [Q&A]
I have a binary file with just a dump of CCSDS packets.  Is there a way to easily import such file info Yamcs archive?  Or shall I write some code to replay the file and feed the data as individual TM packets to Yamcs?

**Comment by fqqb** [comment]
No UI support, but you can add a `FilePollingTmDataLink` link to your instance configuration. For example:

```yaml
dataLinks:
  - name: tm_file
    class: org.yamcs.tctm.FilePollingTmDataLink
    stream: tm_dump
    incomingDir: /path/to/some/directory
```

WIth this, Yamcs will periodically scan `incomingDir`, and when it finds a file, it will split the file in packets and import all contained packets. The use of the `tm_dump` (instead of the usual `tm_realtime`) avoids to forward all this data to realtime clients.

By default `FilePollingTmDataLink` expects packets with CCSDS primary+secundary header, so you may need to configure a different preprocessor options similar as what your regular links use.

See options here: https://docs.yamcs.org/yamcs-server-manual/links/file-polling-tm-data-link/

**Reply by jmwislez** [reply]
Thank you!  File gets read, indeed, but fails with this error message.  
```
java.io.IOException: ASCII header too long, probably not a PaCTS archive file: ' -?☻ ▲R♦ ☻        ☺ '
org.yamcs.tctm.UsocPacketInputStream.readPacket(UsocPacketInputStream.java:88)
org.yamcs.tctm.FilePollingTmDataLink.play(FilePollingTmDataLink.java:113)
org.yamcs.tctm.FilePollingTmDataLink.run(FilePollingTmDataLink.java:86)
java.base/java.lang.Thread.run(Thread.java:833)
```
The files I have contain purely the concatenated CCSDS packets no encapsulation, padding, or separators.

**Reply by fqqb** [reply]
Can you try specifying `org.yamcs.tctm.CcsdsPacketInputStream` as a `packetInputStreamClassName` as part of your link options:

```yaml
dataLinks:
  - name: tm_file
    class: org.yamcs.tctm.FilePollingTmDataLink
    stream: tm_dump
    incomingDir: /path/to/some/directory
    packetInputStreamClassName: org.yamcs.tctm.CcsdsPacketInputStream 
```

(Seems the legacy default UsocPacketInputStream splitter only recognizes CCSDS packets with secondary header, before defaulting to 'PaCTS' format)
