### DISCUSSION TITLE
SLE data link not processing incoming packets

### DISCUSSION THREAD

**Discussion by asalamon-work** [yamcs/yamcs#753] [Q&A]
I'm using https://github.com/visionspacetec/sle-provider to simulate an SLE provider, including a very simple stream of telemetry packets (sle-provider/examples/start_provider.py and sle-provider/examples/data_endpoint.py).

In yamcs.myproject.yaml, I have a datalinks section for SLE:

```
  - name: SLE_IN
    class: org.yamcs.sle.TmSleLink
    sleProvider: GS1
    deliveryMode: timely
    stream: tm_realtime
    frameType: "TM"
    frameLength: 1121
    spacecraftId: 234
    errorDetection: "CRC16"
    packetPreprocessorClassName: com.msss.myproject.MsssPacketPreprocessor
    virtualChannels:
      - vcId: 3
        service: "PACKET"
        packetPreprocessorClassName: com.msss.myproject.MsssPacketPreprocessor
```
And here's my sle.yaml file:

```
CommonSettings: &CommonSettings
    hashAlgorithm: "SHA-1"
    authLevel: NONE
    versionNumber: 4
    myUsername: "user01"
    myPassword:  01020304ABCD
    initiatorId: "SLE_USER"
    responderPortId: "ABC"
    heartbeatInterval: 30
    heartbeatDeadFactor: 3
    spacecraftId: 1929292

Providers:
    GS1:
        <<: *CommonSettings
        peerUsername: "SLE_PROVIDER"
        peerPassword: AB0102030405060708090a0b0c0d0e0f

        cltu:
            host: 127.0.0.1
            port: 55529
            serviceInstance: "sagr=1.spack=VST-PASS0001.fsl-fg=1.cltu=cltu1"

        raf-onlt:
            host: 127.0.0.1
            port: 55529
            serviceInstance: "sagr=1.spack=VST-PASS0001.rsl-fg=1.raf=onlt1"
```

In the Links tab of the YAMCS web UI I see the SLE_IN link, which is bright green (OK, activity), and the In column shows a count that increases every second or so. If I expand the triangle next to that I see "SLE_IN.vc3", which shows as "OK" but not active, and there is no count under the In column.

In my packet preprocessor class I'm generating an event for every incoming packet:

eventProducer.sendWarning("PACKET_RECEIVED", "Packet apid: " + apid + "  sequence: " + seq);

That event code works fine if I put it in the pre processor class for the default udp-in link that get's set up by the quickstart repo.

However, I never see any events from the SLE link. I also don't see any error messages in the UI or the log files that might be related to failing to parse incoming packets. Maybe because something about the virtual channel needs to be configured correctly?

Any suggestions what might be wrong, or where to look next would be appreciated.
