### DISCUSSION TITLE
Subject: Assistance with Yamcs Data-Link Setup and Algorithm Integration

### DISCUSSION THREAD

**Discussion by thstasy** [yamcs/yamcs#965] [Q&A]
Dear Yamcs Team,

Thank you for your previous help. I have since switched to UDP for our telemetry setup.

The goal of our project is to replace a Python script with Yamcs, storing data in RocksDB and transferring it to OpenMCT for real-time visualization. So far, I've set up multiple UDP telemetry data links (FSW_UDP_Link, DAQ_AVI_UDP_Link, etc.) for data reception, and the links are functioning well.

Here is the working **yamcs.myproject.yaml**:
```
services:
  - class: org.yamcs.archive.XtceTmRecorder
  - class: org.yamcs.archive.ParameterRecorder
  - class: org.yamcs.archive.AlarmRecorder
  - class: org.yamcs.archive.EventRecorder
  - class: org.yamcs.archive.ReplayServer
  - class: org.yamcs.parameter.SystemParametersService
  - class: org.yamcs.ProcessorCreatorService
    args:
      name: realtime
      type: realtime
  - class: org.yamcs.archive.CommandHistoryRecorder
  - class: org.yamcs.parameterarchive.ParameterArchive
    args:
      realtimeFiller:
        enabled: true
      backFiller:
        enabled: false
        warmupTime: 60
  - class: org.yamcs.plists.ParameterListService
  - class: org.yamcs.timeline.TimelineService

# Data links for telemetry reception via UDP
dataLinks:
  # Flight Software (FSW) Telemetry via UDP
  - name: FSW_UDP_Link
    class: org.yamcs.tctm.UdpTmDataLink
    stream: tm_realtime
    port: 5001
    packetPreprocessorClassName: org.yamcs.tctm.GenericPacketPreprocessor
    packetPreprocessorArgs:
      timestampOffset: 12
      seqCountOffset: 4
      byteOrder: BIG_ENDIAN

  # DAQ AVI Telemetry via UDP
  - name: DAQ_AVI_UDP_Link
    class: org.yamcs.tctm.UdpTmDataLink
    stream: tm_realtime
    port: 5002
    packetPreprocessorClassName: org.yamcs.tctm.GenericPacketPreprocessor
    packetPreprocessorArgs:
      timestampOffset: 12
      seqCountOffset: 4
      byteOrder: BIG_ENDIAN

  # DAQ ACC Telemetry via UDP
  - name: DAQ_ACC_UDP_Link
    class: org.yamcs.tctm.UdpTmDataLink
    stream: tm_realtime
    port: 5003
    packetPreprocessorClassName: org.yamcs.tctm.GenericPacketPreprocessor
    packetPreprocessorArgs:
      timestampOffset: 12
      seqCountOffset: 4
      byteOrder: BIG_ENDIAN

  # IMU Payload Telemetry via UDP
  - name: IMU_Payload_UDP_Link
    class: org.yamcs.tctm.UdpTmDataLink
    stream: tm_realtime
    port: 5006
    packetPreprocessorClassName: org.yamcs.tctm.GenericPacketPreprocessor
    packetPreprocessorArgs:
      timestampOffset: 12
      seqCountOffset: 4
      byteOrder: BIG_ENDIAN

  # GPSR Telemetry via UDP
  - name: GPSR_UDP_Link
    class: org.yamcs.tctm.UdpTmDataLink
    stream: tm_realtime
    port: 5004
    packetPreprocessorClassName: org.yamcs.tctm.GenericPacketPreprocessor
    packetPreprocessorArgs:
      timestampOffset: 12
      seqCountOffset: 4
      byteOrder: BIG_ENDIAN

  # RTK Telemetry via UDP
  - name: RTK_UDP_Link
    class: org.yamcs.tctm.UdpTmDataLink
    stream: tm_realtime
    port: 5005
    packetPreprocessorClassName: org.yamcs.tctm.GenericPacketPreprocessor
    packetPreprocessorArgs:
      timestampOffset: 12
      seqCountOffset: 4
      byteOrder: BIG_ENDIAN

  # Output for commands via UDP
  - name: udp-out
    class: org.yamcs.tctm.UdpTcDataLink
    stream: tc_realtime
    host: localhost
    port: 10025
    commandPostprocessorClassName: org.yamcs.tctm.GenericCommandPostprocessor
    #commandPostprocessorClassName: org.yamcs.tctm.CommandPostprocessor
    commandPostprocessorArgs:
      byteOrder: BIG_ENDIAN

# Mission Database Configuration (XTCE Loader)
mdb:
  - type: xtce
    args:
      file: mdb/xtce.xml  # Path to your XTCE XML file

# Stream configurations
streamConfig:
  tm:
    - name: "tm_realtime"
      processor: "realtime"
    - name: "tm_dump"
  cmdHist: ["cmdhist_realtime", "cmdhist_dump"]
  event: ["events_realtime", "events_dump"]
  param: ["pp_realtime", "pp_dump", "sys_param", "proc_param"]
  parameterAlarm: ["alarms_realtime"]
  tc:
    - name: "tc_realtime"
      processor: "realtime"

```
Next, I added a custom algorithm (**CustomTelemetryProcessingAlgorithm.java**) for data conversion, but now I am encountering errors like “`Unknown argument XXX`” when running Yamcs:

```
[INFO] --- yamcs-maven-plugin:1.3.1:run (default-cli) @ myproject ---
[INFO] Creating configuration at /home/stasy/arrc_work/quickstart/target/yamcs
<6>Logging enabled using /home/stasy/arrc_work/quickstart/target/yamcs/etc/logging.properties
<6>Loading service HttpServer
<6>Creating or loading tablespace _global
<6>_global: Opened tablespace database /home/stasy/arrc_work/quickstart/yamcs_data/_global.rdb
<6>_global: Records: ~3, metadata records: ~18, maxTbsIndex: 8
<6>_global: Loaded 3 tables for instance _global
<6>Loading online instance 'myproject'
<3>yamcs.myproject.yaml: Unknown argument mdb[0]->config_
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.231 s
[INFO] Finished at: 2024-10-16T10:52:43+08:00
```

At this stage, the `yamcs.myproject.yaml `file is as follows: 
```
# Minimal mdb configuration to avoid errors
mdb:
  # Load XTCE database file (assuming xtce.xml is located in the mdb directory)
  - type: xtce
    config:
      files: 
        - mdb/xtce.xml  # Adjust this path if your XTCE file is located elsewhere

# Data Links Configuration
dataLinks:
  - name: FSW_UDP_Link
    type: udp
    host: localhost
    port: 10000
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: DAQ_AVI_UDP_Link
    type: udp
    host: localhost
    port: 5002
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: DAQ_ACC_UDP_Link
    type: udp
    host: localhost
    port: 5003
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: GPSR_UDP_Link
    type: udp
    host: localhost
    port: 5004
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: RTK_UDP_Link
    type: udp
    host: localhost
    port: 5005
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: IMU_Payload_UDP_Link
    type: udp
    host: localhost
    port: 5006
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: IPCAM1_UDP_Link
    type: udp
    host: localhost
    port: 5007
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: IPCAM2_UDP_Link
    type: udp
    host: localhost
    port: 5008
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
  - name: IPCAM3_UDP_Link
    type: udp
    host: localhost
    port: 5009
    tmProcessor: 
      algorithm: 
        className: com.example.myproject.algorithms.CustomTelemetryProcessingAlgorithm
```
Could you advise on how to resolve this issue and determine the correct arguments for Yamcs? Could it also be related to changes in the `xtce.xml` file?

Thank you for your continued support.

Best regards,
Tsai-Hsuan Stasy HSIEH
