### ISSUE TITLE
Packet Viewer offline use / MDB conversion

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs#461]
I have used the packet viewer in an "online" configuration for the last months and its an awesome tool to quickly check some raw data. I am currently hosting my MDB in Yamcs Server in the XLS / Excel Format which works great. However, the packet viewer wants a copy of the MDB for offline use. I am having trouble in integrating the MDB into the packet viewer - which are the steps needed to accomplish this?

Thanks

Nico

**Comment by fqqb** [comment]
Sorry for late reply here. Something like this should do:

Define how Packet Viewer can split the file in packets in `etc/packet-viewer.yaml`:

````
packetInputStreamClassName: org.yamcs.tctm.CcsdsPacketInputStream
packetInputStreamArgs:
  maxPacketLength: 2000
````

And in `etc/mdb.yaml`, copy the MDB definitions that you use in yamcs.[instance].yaml.
For example:

````
someName:
  - type: "sheet"
    spec: "/path/to/mdb/simulator-ccsds.xls"
    subLoaders:
      - type: "sheet"
        spec: “/path/to/mdb/landing.xls"
````

`someName` will appear in the dropdown when you open a file.
