### ISSUE TITLE
Should be able to specify destination entityId when sending CFDP file

### ISSUE THREAD

**Issue by AdamElliott-AB** [yamcs/yamcs#462]

**Comment by xpromache** [comment]
It is possible to specify the destination entity id (key _destinationId_ ) in the configuration of the CFDP service:

```
services:
...
  - class: org.yamcs.cfdp.CfdpService
    args:
     sourceId: 5
     destinationId: 24
     sequenceNrLength: 4
     maxPduSize: 512
     incomingBucket: "cfdpDown"
     eofAckTimeout: 3000
     maxEofResendAttempts: 5
```
Or do you mean to specify it for each file transfer individually when starting the transfer (in case there are multiple destinations)?
