### ISSUE TITLE
how to enable file download option in File Transfer tab for CFDP service

### ISSUE THREAD

**Issue by spreston93** [yamcs/yamcs#535]
Hello,
I have used the CFDP example to get up and running with file transfer. I have been able to successfully upload files, however I would like to be able to download files from the remotes as well. Using the HTTP API, I can see that my current instance does not have the download option available:

```
curl 'localhost:8090/api/filetransfer/myproject/services'
```
outputs:
```
...
    "capabilities": {
      "upload": true,
      "download": false,
      "reliability": true,
      "remotePath": true
...
```
which shows the download option as false so the download button does not appear in the yamcs web interface like the upload button does. 

My global yamcs.yaml config has 2 buckets for up and down (and I have created the corresponding directories):
```
...
buckets:
  - name: cfdpUp
    path: ../../cfdpUp
  - name: cfdpDown
    path: ../../cfdpDown
...
```
A side note: I tried to create my buckets in my local instance config, but I get a yaml parsing error. So I made them global buckets. 

I have also added the cfdp service to my instance configuration:
```
...

- class: org.yamcs.cfdp.CfdpService
    name: cfdp0
    args:
      sequenceNrLength: 4
      maxPduSize: 512
      incomingBucket: "cfdpDown"
      inStream: "cfdp_in"
      outStream: "cfdp_out"
      eofAckTimeout: 3000
      eofAckLimit: 3
      sleepBetweenPdus: 1000
      localEntities:
        - name: id1
          id: 11
          bucket: cfdpDown
      remoteEntities:
        - name: target1
          id: 7
          bucket: cfdpDown
      senderFaultHandlers:
        AckLimitReached: suspend
      receiverFaultHandlers:
        AckLimitReached: suspend
...
```

I have also included the extra_streams.sql file in my stream configuration:
```
streamConfig:
  tm:
    - name: "tm_realtime"
      processor: "realtime"
    - name: "tm2_realtime"
      rootContainer: "/YSS/SIMULATOR/tm2_container"
      processor: "realtime"
    - name: "tm_dump"
  invalidTm: "invalid_tm_stream"
  cmdHist: ["cmdhist_realtime", "cmdhist_dump"]
  event: ["events_realtime", "events_dump"]
  param: ["pp_realtime", "sys_param", "proc_param"]
  parameterAlarm: ["alarms_realtime"]
  eventAlarm: ["event_alarms_realtime"]
  tc: ["tc_realtime"]
  sqlFile: "etc/extra_streams.sql"
```

What am I missing? How do I get the download button to appear? The [HTTP api documentation](https://docs.yamcs.org/yamcs-http-api/file-transfer/list-file-transfer-services/) hints at the button being a possibility but it does not look like the CFDP example has the button enabled either. 

```
interface FileTransferCapabilities {
...
  //if true, yamcs-web shows a button for initiating an upload
  upload: boolean;

  //if true, yamcs-web shows a button for initiating a download
  download: boolean;
...
}
```
