### ISSUE TITLE
Startup error when a bucket is configured and its directory does not exist

### ISSUE THREAD

**Issue by jdiez17** [yamcs/yamcs#991]
We have the following config in `src/main/etc/yamcs.yml`:

```yaml
buckets:
  - name: cfdpUp
    # the path here is relative to the current directory as set by maven
    # and it maps to examples/cfdp/target/yamcs
    path: cfdpUp
```

If the directory does not exist (i.e. during a first run of Yamcs), we get the following error:

```
YamcsServer Failure while attempting to validate configuration: Failed to load buckets: Directory 'cfdpUp'(/home/user/dev/rccn/yamcs/yamcs-instance/target/yamcs/cfdpUp) not found
```

Is there a reason why Yamcs does not create the directory automatically?
